# Generated by Django 4.1.2 on 2023-10-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prof', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('telephone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horaireprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
                ('Horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.horaire')),
                ('Professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.professeur')),
            ],
        ),
    ]
