# Generated by Django 4.1.2 on 2023-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='nombre_seance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horaireprof',
            name='jour',
            field=models.CharField(max_length=10),
        ),
    ]
