# Generated by Django 4.1.2 on 2023-10-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matiere', '0001_initial'),
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('Professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.professeur')),
            ],
        ),
    ]
