# Generated by Django 4.1.2 on 2023-10-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('niveau', models.IntegerField()),
                ('nb_eleve', models.IntegerField()),
                ('nb_seance', models.IntegerField()),
            ],
        ),
    ]
