# Generated by Django 4.1.2 on 2023-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='optionnel',
            field=models.BooleanField(default=False),
        ),
    ]
